### ISSUE TITLE
Interesting ideal

### ISSUE THREAD

**Issue by thaeviction** [lschierer/Game-EvonyTKR#1]
So newbie here, but this is exactly one of my hope of possibilities! a simple way to export directly from in-app... so don't know if your intentions were monitor only but
.. one of my ideals is to grab real time chat (and possibly in-game mail) and be able to view and/or respond offline. Is it possible to mimic the creds enough to do two way chat or even just offline monitor? I feel as cheap as Evony is they have to be using a 3rd party chat service api whatever so shouldn't be too hard... 

Second rabbit hole for thought... Simple stripped down emulator/launcher that is compatible with ESB with no bulky rss heavy crap running in background. Paid versions of BS or MEmu would be dreamy at this point. Resets every 2/3 months is O L D.  

Thanks!!

**Comment by lschierer** [comment]
My goal is just taking some hand generated data files about the generals, the skill books, the art work, so on.

I can then take that data to do two things.
1.  I can combine it into tables to allow for humans to absorb and make comparisons more easily
2.  I can ask a user a handful of questions about their account, and use that as variables to make suggestions/recommendations. 

I am not looking at making a bot, nor in any way hacking the game to extract anything automatically.

**Comment by thaeviction** [comment]
Yeah I don’t cross the threshold of cheating , changing or hacking. Just
thought it would be cool to explore or utilize that data as well.
Especially the full data of reports. It’s exhaustive to try to enter all
the data so automations would be ideal. Absent of Evony exclusivity maybe
you could tell me generally in theory if it is possible? I have no
experience in coding or scripting outside of my high school Ti-83+
calculator 😆 I appreciate the response

**Comment by lschierer** [comment]
so if you were writing a bot, you could essentially write a screen reader that would interact with an emulator, either blue stacks or Memu, and would control the game in your place.  It would then have access to the contents of your reports the same way you would - as it would be playing the game in place of you.  That would not be hacking, and would be ethically legal, though still potentially against the terms of service.  Such a bot could read your mail, run character recognition (effectively OCR) on the reports, and get the data from your monster hunting that way, to generate the sorts of data files I use.  

I have no *ethical* concerns with obtaining data this way.  It is simply not within the scope of this project.  If someone else were to do that, I'd be happy to consume the resulting data files.
